# installing dependencies
before_script:
    - apt-get update && apt-get -qq install python-pip m4
    - pip install git+https://github.com/goldmann/docker-squash@master 'docker<3'
    - docker info
    - docker-squash --version
    - m4 --version

# different stages
stages:
    - test
    - base
    - main
    - late # used for redis because the registry is down while updating the redis

# test if building of the files is possible
test_files:
    script:
        - ./docker-builder.sh build-files
    stage: test

# template for build jobs
.docker_build_image: &docker_build_image
    script:
        - ./docker-builder.sh build-image $CI_BUILD_NAME
        - ./docker-builder.sh publish-image $CI_BUILD_NAME
    stage: main
    only:
        - v1.7

# ubuntu base image
base:
    <<: *docker_build_image
    stage: base

# custom docker images
apache-php56:
    <<: *docker_build_image

apache-php70:
    <<: *docker_build_image

apache-php71:
    <<: *docker_build_image

apache-php72:
    <<: *docker_build_image

apache:
    <<: *docker_build_image

bind:
    <<: *docker_build_image

cloudflare-railgun:
    <<: *docker_build_image

docker:
    <<: *docker_build_image

elasticsearch:
    <<: *docker_build_image

golang:
    <<: *docker_build_image

icinga2:
    <<: *docker_build_image

java:
    <<: *docker_build_image

kibana:
    <<: *docker_build_image

logstash-forwarder:
    <<: *docker_build_image

logstash:
    <<: *docker_build_image

mariadb:
    <<: *docker_build_image

memcached:
    <<: *docker_build_image

mongodb:
    <<: *docker_build_image

nextcloud:
    <<: *docker_build_image

nginx-php56:
    <<: *docker_build_image

nginx-php70:
    <<: *docker_build_image

nginx-php71:
    <<: *docker_build_image

nginx-php72:
    <<: *docker_build_image

nginx:
    <<: *docker_build_image

node:
    <<: *docker_build_image

openldap:
    <<: *docker_build_image

owncloud:
    <<: *docker_build_image

php56:
    <<: *docker_build_image

php70:
    <<: *docker_build_image

php71:
    <<: *docker_build_image

php72:
    <<: *docker_build_image

postgres:
    <<: *docker_build_image

puppet-client:
    <<: *docker_build_image

redis:
    <<: *docker_build_image
    stage: late

ruby:
    <<: *docker_build_image

squid:
    <<: *docker_build_image

symfony2:
    <<: *docker_build_image

symfony3:
    <<: *docker_build_image

symfony4:
    <<: *docker_build_image

tomcat:
    <<: *docker_build_image

wordpress-nginx-w3tc:
    <<: *docker_build_image

wordpress:
    <<: *docker_build_image
