variables:
    DOCKER_HOST: tcp://localhost:2375

stages:
     - build

build:
    stage: build
    script:
        - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
        - git checkout -b $CI_COMMIT_REF_NAME # Checkout branch explicitly due to build script logic
        - ./build.sh --push
    only:
        - branches
    services:
        - docker:stable-dind
    tags:
        - kubernetes
