variables:
    DOCKER_HOST: tcp://docker:2375/

stages:
    - test
    - build

.base_job:
    image: docker:stable
    stage: build
    services:
        - docker:stable-dind
    tags:
        - kubernetes

validate_readme:
    extends: .base_job
    stage: test
    allow_failure: true # Link checking fails sometimes because of sloppy third party servers
    script:
        - ./validate-readme.sh
    only:
        - v2.0
        - v2.1-dev

build:
    extends: .base_job
    stage: build
    script:
        - apk add --no-cache git
        - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
        - git checkout -B $CI_COMMIT_REF_NAME # Checkout branch explicitly due to build script logic
        - ./build.sh --push
    only:
        - v2.0
        - v2.1-dev

update_readme:
    extends: .base_job
    stage: build
    script:
        - ./update-readme.sh
    only:
        - v2.0
        - v2.1-dev
